
name: Visual Regression Tests

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          corepack enable
          pnpm install

      - name: Install Playwright browsers
        run: pnpm exec playwright install --with-deps

      - name: Start Nuxt server
        run: pnpm run build && pnpm run preview &
        env:
          NUXT_PUBLIC_BASE_URL: http://localhost:3000
        continue-on-error: true

      - name: Wait for Nuxt to boot
        run: sleep 10

      - name: Run visual tests
        run: pnpm exec playwright test
