name: Generate Weekly Top Calculators Report

on:
  schedule:
    - cron: '0 0 * * 0'  # Every Sunday at midnight UTC
  workflow_dispatch:

jobs:
  weekly-report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Generate weekly report
        run: npm run report:weekly

      - name: Commit and push report
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add public/analytics/weekly-report.json
          git commit -m "chore: update weekly top calculators report"
          git push